import { specimenAssetFor, type SpecimenAsset } from '../scene/specimens/assetRegistry'
import catalogJson from './visual-catalog.v1.json'

// Typed view of src/catalog/visual-catalog.v1.json, generated by
// scripts/specimens/build_visual_catalog.mjs. Categories, water types and statuses are open string
// sets with a known-vocabulary list next to them, so a future `plant` category or `freshwater` water
// type only needs a builder rerun, not a schema change.

export const VISUAL_CATALOG_SCHEMA = 'pocket-aquarium.visual-catalog/v1'

export const KNOWN_CATEGORIES = ['fish', 'coral', 'invertebrate', 'cleanup_crew'] as const
export type KnownCategory = (typeof KNOWN_CATEGORIES)[number]
export type SpecimenCategory = KnownCategory | (string & {})

export const KNOWN_WATER_TYPES = ['saltwater', 'freshwater'] as const
export type WaterType = (typeof KNOWN_WATER_TYPES)[number] | (string & {})

export const ASSET_STATUSES = ['accepted', 'candidate', 'provisional', 'failed', 'missing'] as const
export type AssetStatus = (typeof ASSET_STATUSES)[number]

export interface CatalogStatistics {
  readonly triangles: number | null
  readonly materials: number | null
  readonly bones: number | null
  readonly clips: readonly string[]
}

export interface CatalogCandidate {
  readonly name: string
  readonly variantId: string | null
  readonly displayName: string
  /** `awaiting_user_acceptance` for built packages, `missing` when the manifest is absent or unparsable. */
  readonly state: string
  readonly manifest: 'present' | 'missing' | 'unparsable'
  readonly validatorStatus: string | null
  readonly buildStatus: string
  readonly buildFailedStage: string | null
  readonly assetVersion: string | null
  readonly loadable: boolean
  readonly glb: string | null
  readonly glbSha256: string | null
  readonly glbSha256Verified: boolean
  readonly geometryDigest: string | null
  readonly statistics: CatalogStatistics | null
  readonly clipRoles: Readonly<Record<string, string>> | null
  readonly clipLoops: Readonly<Record<string, boolean>> | null
  readonly referenceSizeMeters: number | null
  readonly userApproved: boolean
  readonly renders: { readonly authorPreview: string | null; readonly threeView: string | null }
}

export interface CatalogRow {
  readonly id: string
  readonly displayName: string
  readonly scientificLabel: string | null
  readonly taxonomyConfidence: string | null
  readonly category: SpecimenCategory
  readonly waterType: WaterType | null
  readonly bodyPlan: string | null
  readonly referenceSize: { readonly meters: number | null; readonly kind: string | null }
  readonly referenceGrade: string | null
  readonly assetStatus: AssetStatus
  readonly assetVersion: string | null
  readonly provisional: unknown
  readonly accepted: {
    readonly glb: string | null
    readonly sha256: string | null
    readonly clips: readonly string[]
    readonly statistics: CatalogStatistics | null
  }
  readonly candidates: readonly CatalogCandidate[]
  readonly variants: readonly { readonly id: string; readonly displayName: string }[]
  readonly clipRoles: Readonly<Record<string, string>> | null
  readonly provenance: {
    readonly source: string
    readonly sourceReferences: string | null
    readonly referenceGrade: string | null
  }
  readonly visualDebt: readonly string[]
}

export interface VisualCatalog {
  readonly schemaVersion: typeof VISUAL_CATALOG_SCHEMA
  readonly generatedAt: string
  readonly categories: readonly SpecimenCategory[]
  readonly assetStatuses: readonly AssetStatus[]
  readonly userApprovals: Readonly<Record<string, string>>
  readonly summary: {
    readonly rows: number
    readonly byCategory: Readonly<Record<string, number>>
    readonly byStatus: Readonly<Record<string, number>>
    readonly candidates: { readonly total: number; readonly loadable: number; readonly missing: number; readonly userApproved: number }
  }
  readonly rows: readonly CatalogRow[]
}

export const visualCatalog = catalogJson as unknown as VisualCatalog

const CATEGORY_LABELS: Readonly<Record<KnownCategory, string>> = {
  fish: 'Fish',
  coral: 'Coral',
  invertebrate: 'Invertebrates',
  cleanup_crew: 'Cleanup crew',
}

export function categoryLabel(category: SpecimenCategory) {
  return (CATEGORY_LABELS as Record<string, string>)[category] ?? category.replaceAll('_', ' ').replace(/^./, (c) => c.toUpperCase())
}

export function categoryOrder(catalog: Pick<VisualCatalog, 'categories' | 'rows'> = visualCatalog): readonly SpecimenCategory[] {
  const seen = new Set<string>(catalog.categories)
  const extra = [...new Set(catalog.rows.map((row) => row.category))].filter((category) => !seen.has(category)).sort()
  return [...catalog.categories, ...extra]
}

/** Rows grouped by category in catalog order; accepted rows lead each group, the rest keep the builder's displayName sort. */
export function rowsByCategory(rows: readonly CatalogRow[] = visualCatalog.rows, categories = categoryOrder({ categories: visualCatalog.categories, rows })) {
  return categories
    .map((category) => {
      const members = rows.filter((row) => row.category === category)
      return {
        category,
        label: categoryLabel(category),
        rows: [...members.filter((row) => row.assetStatus === 'accepted'), ...members.filter((row) => row.assetStatus !== 'accepted')],
      }
    })
    .filter((group) => group.rows.length > 0)
}

export function catalogRow(speciesId: string, rows: readonly CatalogRow[] = visualCatalog.rows) {
  return rows.find((row) => row.id === speciesId)
}

/** Typed accessor for rows the runtime may load. Resolution still goes through the untouched registry, so candidates never leak in. */
export function acceptedSpecimenAssets(rows: readonly CatalogRow[] = visualCatalog.rows): readonly { readonly row: CatalogRow; readonly asset: SpecimenAsset }[] {
  const accepted: { row: CatalogRow; asset: SpecimenAsset }[] = []
  for (const row of rows) {
    if (row.assetStatus !== 'accepted') continue
    const asset = specimenAssetFor(row.id)
    if (asset) accepted.push({ row, asset })
  }
  return accepted
}

// Shared-scale framing. The camera and ruler are fixed to one reference span so an 8 cm clownfish,
// a 3 cm snail and the 90 cm epaulette shark read at their real relative sizes. Spans beyond the
// clamp would shrink the small species to a few pixels, so the span is clamped and the UI notes it.
export const SHARED_SCALE_CLAMP_METERS = 0.5
export const SHARED_SCALE_BAR_METERS = 0.1

export interface SharedScaleSpan {
  readonly spanMeters: number
  readonly largestMeters: number
  readonly largestId: string | null
  readonly largestDisplayName: string | null
  readonly clamped: boolean
}

export function sharedScaleSpan(rows: readonly Pick<CatalogRow, 'id' | 'displayName' | 'referenceSize'>[] = visualCatalog.rows, clampMeters = SHARED_SCALE_CLAMP_METERS): SharedScaleSpan {
  let largest: Pick<CatalogRow, 'id' | 'displayName' | 'referenceSize'> | undefined
  for (const row of rows) {
    const meters = row.referenceSize.meters
    if (meters === null || !Number.isFinite(meters) || meters <= 0) continue
    if (!largest || meters > (largest.referenceSize.meters ?? 0)) largest = row
  }
  const largestMeters = largest?.referenceSize.meters ?? SHARED_SCALE_BAR_METERS
  const spanMeters = Math.min(largestMeters, clampMeters)
  return {
    spanMeters,
    largestMeters,
    largestId: largest?.id ?? null,
    largestDisplayName: largest?.displayName ?? null,
    clamped: largestMeters > clampMeters,
  }
}
